### PR TITLE
Drop support Django 1.11 and add Python3.9 support.

### PR DESCRIPTION
**Pull request by hramezani**

### CODE REVIEW

**Comment by smithdc1** [comment]
A couple of the requirements files have Django pinned to version 1.5. Not sure if adjusting these (could remove the pin entirely?) is out of scope here.

**Comment by hramezani** [comment]
> A couple of the requirements files have Django pinned to version 1.5. Not sure if adjusting these (could remove the pin entirely?) is out of scope here.

Thanks, @smithdc1 . I missed them. I updated them to `Django>=2.2`.

**Comment by mgrdcm** [comment]
Look at all that glorious removed code!  😍

**Comment by mgrdcm** [comment]
How would you feel about adding in the supported Django versions shield too since we're adding the Python one in this PR?  https://img.shields.io/pypi/djversions/django-embed-video.svg

**Comment by hramezani** [comment]
> How would you feel about adding in the supported Django versions shield too since we're adding the Python one in this PR? https://img.shields.io/pypi/djversions/django-embed-video.svg

Good idea :+1:
Done!

**Review by smithdc1 — APPROVED** [review]

**Comment by mgrdcm** [comment]
This looks great to me.  One question - since we are supporting back to Django 2.2 and that supports Python 3.5 should we add 3.5 to the support/tests even though 3.5 is EOL'd as of September 2020?  Since it's an LTS I'd think we should but I won't fight over it ;)

**Review by mgrdcm — APPROVED** [review]

**Comment by mgrdcm** [comment]
Oh and of course need to make sure the release that includes this is a breaking/major change version so like 2.0.0 right?

**Comment by smithdc1** [comment]
It seems this project hasn't supported python 3.5 for a while. Would seem odd to add it now as it's eol. Agree generally that Django 2.2 still supports py3.5 so it's good if packages can follow this.

Not sure about need for it to be a major version bump. I'm not seeing this approach across many of the Django packages. But if that's the policy for this package it should be followed.  🤷

**Comment by hramezani** [comment]
@mgrdcm About Python3.5, it would be good to read this [comment](https://github.com/jazzband/django-axes/pull/679#issuecomment-730501965) from @aleksihakli. I think we can ignore Python3.5 unless there is a strong reason to keep it.

**Comment by hramezani** [comment]
> Not sure about need for it to be a major version bump. I'm not seeing this approach across many of the Django packages. But if that's the policy for this package it should be followed.

Agree with @smithdc1 :+1:

**Comment by mgrdcm** [comment]
> @mgrdcm About Python3.5, it would be good to read this comment from @aleksihakli. I think we can ignore Python3.5 unless there is a strong reason to keep it.

Agreed - sounds good to me on not adding support for it now since it's EOL'd!

> Not sure about need for it to be a major version bump. I'm not seeing this approach across many of the Django packages. But if that's the policy for this package it should be followed. 🤷

Good point!  I don't see that this project explicitly requires it but I'd think that dropping support for a major Django version (even if EOL'd) would qualify as breaking.  I don't see a reason *not* to make it a breaking change in any case.  But not gonna fight about this either!

Thanks to @hramezani for this PR and everyone who's contributing to this project!

**Pull request merged**
