### PR TITLE
Enable default HTTPS support

### PR DESCRIPTION
**Pull request by marcosguedes**
All supplied backends support HTTPS. I think it's fine to support HTTPS by default

### CODE REVIEW

**Comment by joelschopp** [comment]
Agree, we should switch to https being default

**Comment by CedricCarrard** [comment]
@marcosguedes Please look to correct the tests thanks

**Comment by marcosguedes** [comment]
@CedricCarrard thanks for pointing that out, I'll handle it asap

**Comment by marcosguedes** [comment]
@CedricCarrard Fixed. Apologies for the wait, I've never used tests like these before, I've learned a lot :)

**Comment by marcosguedes** [comment]
How odd... it retrieved a vimeo thumbnail on http after requesting https on Django==1.10.x . I've tested it 5 times and it was a success everytime. Is this a vimeo issue?

**Comment by mgrdcm** [comment]
Hey!

Even if secure/SSL is the default, not sure we'd want to remove any of the tests for `http` URLs, since those are still valid too.

**Comment by CedricCarrard** [comment]
@mgrdcm  Would you have time to help finish the pull-request? I'm waiting on the pull request to create a new version.

**Comment by mgrdcm** [comment]
I can, but might be a day or two...

**Comment by marcosguedes** [comment]
Hi @CedricCarrard @mgrdcm so sorry, heavy workload these past days and I completely forgot. Will try again today in about 5h.

Cheers and thank you for your patience!

**Comment by marcosguedes** [comment]
Hi there @mgrdcm , @CedricCarrard ! Apologies for being late. Is it ok right now? Not sure if I git-reverted successfully

**Comment by CedricCarrard** [comment]
@mgrdcm @marcosguedes good work guys thanks.

**Pull request merged**
