### PR TITLE
Update CHANGES.rst for release 1.4.0

### PR DESCRIPTION
**Pull request by mgrdcm**
Figure it's time to prepare a release, and so updating the changelog.  I think this covers all the things that have [changed since 1.3.3](https://github.com/jazzband/django-embed-video/compare/1.3.3...master).

_Normally I'd think this should be a breaking 2.0 change since we're dropping support for a few Django versions but it appears that hasn't been the pattern in this project so just going with 1.4.0._

### CODE REVIEW

**Comment by mgrdcm** [comment]
@hramezani Did I miss anything in the changelog?  You good with doing a release now?  Have you done one, or does @aleksihakli need to do it?

**Comment by aleksihakli** [comment]
Hey @mgrdcm! You can see the people who can do the releases at the project Jazzband page:

https://jazzband.co/projects/django-embed-video

You @mgrdcm and me @aleksihakli can push the releases from the Jazzband page to PyPI at the current moment.

**Comment by aleksihakli** [comment]
I reviewed and upstreamed the changes, but the rST file had a formatting error it needs fixed for upstreaming. I opened a PR for those, as soon as we get that merged we can bake the 1.4.0 release :)

**Comment by mgrdcm** [comment]
> I reviewed and upstreamed the changes, but the rST file had a formatting error it needs fixed for upstreaming. I opened a PR for those, as soon as we get that merged we can bake the 1.4.0 release :)

Ahh yes, sorry I didn't mean for that PR to get merged yet was just trying to see if we had everything in there before finalizing the date and whatnot.  I had it as a Draft but apparently that can be overridden!  :)

**Comment by mgrdcm** [comment]
> Hey @mgrdcm! You can see the people who can do the releases at the project Jazzband page:
> 
> https://jazzband.co/projects/django-embed-video
> 
> You @mgrdcm and me @aleksihakli can push the releases from the Jazzband page to PyPI at the current moment.

Great, thanks!  Sorry I haven't actually handled a release yet since being designated a lead.

**Pull request merged**
