### PR TITLE
Add GitHub actions CI pipeline

### PR DESCRIPTION
**Pull request by aleksihakli**
Implementation has been copied over from jazzband/django-axes

### CODE REVIEW

**Comment by hramezani** [comment]
`Travis CI build status` badge in `README` has to be replaced with Github actions

**Comment by jezdez** [comment]
In some of the later versions of the release file we've stopped using the pip cache since it was not worth the extra complexity compared the the gains (e.g. GHA cache is invalidated every 2 weeks automatically).

**Comment by aleksihakli** [comment]
> `Travis CI build status` badge in `README` has to be replaced with Github actions

I'll check this out as well 👍 

> In some of the later versions of the release file we've stopped using the pip cache since it was not worth the extra complexity compared the the gains (e.g. GHA cache is invalidated every 2 weeks automatically).

Good note, thanks. I'll deprecate the cache setup from here 👍

**Comment by aleksihakli** [comment]
Updated the README badge and deprecated pip cache from here and jazzband/django-axes as well.

**Comment by jezdez** [comment]
> Updated the README badge and deprecated pip cache from here and jazzband/django-axes as well.

Sorry, I only meant the release workflow, not the test workflow which is run much more often and where caching actually helps a lot.

**Comment by aleksihakli** [comment]
> > Updated the README badge and deprecated pip cache from here and jazzband/django-axes as well.
> 
> Sorry, I only meant the release workflow, not the test workflow which is run much more often and where caching actually helps a lot.

Restored the cache in the test phase, disable in releases.

@jezdez Travis CI is reaaaaally slooooow, could it possibly be disabled here in favour of GitHub actions? The project should be mostly ported for them. I'm not certain if they require the Jazzband PyPI mirror key for correct functionality on project level?

**Review by JayantGoel001 — APPROVED** [review]

**Comment by jezdez** [comment]
> > > Updated the README badge and deprecated pip cache from here and jazzband/django-axes as well.
> > 
> > 
> > Sorry, I only meant the release workflow, not the test workflow which is run much more often and where caching actually helps a lot.
> 
> Restored the cache in the test phase, disable in releases.
> 
> @jezdez Travis CI is reaaaaally slooooow, could it possibly be disabled here in favour of GitHub actions? The project should ported from Travis to GH now.

Done.

> I'm not certain if it requires the Jazzband PyPI mirror key for correct release functionality on project level?

Yeah, lemme do this tomorrow when I'm in the office, don't merge this yet.

PS: I've added this PR to the tracking project: https://github.com/orgs/jazzband/projects/1

**Comment by aleksihakli** [comment]
> > > > Updated the README badge and deprecated pip cache from here and jazzband/django-axes as well.
> > > 
> > > 
> > > Sorry, I only meant the release workflow, not the test workflow which is run much more often and where caching actually helps a lot.
> > 
> > 
> > Restored the cache in the test phase, disable in releases.
> > @jezdez Travis CI is reaaaaally slooooow, could it possibly be disabled here in favour of GitHub actions? The project should ported from Travis to GH now.
> 
> Done.
> 
> > I'm not certain if it requires the Jazzband PyPI mirror key for correct release functionality on project level?
> 
> Yeah, lemme do this tomorrow when I'm in the office, don't merge this yet.
> 
> PS: I've added this PR to the tracking project: https://github.com/orgs/jazzband/projects/1

It looks like this isn't able to merge either since the Travis job won't trigger anymore and the status check is still required, hehe. If you can merge this later that would be nice.

The master branch is still pending a 1.4.0 release. The changelog and everything else is ready for running a release once the PyPI mirror keys are updated.

**Comment by jezdez** [comment]
> > > > > Updated the README badge and deprecated pip cache from here and jazzband/django-axes as well.
> > > > 
> > > > 
> > > > Sorry, I only meant the release workflow, not the test workflow which is run much more often and where caching actually helps a lot.
> > > 
> > > 
> > > Restored the cache in the test phase, disable in releases.
> > > @jezdez Travis CI is reaaaaally slooooow, could it possibly be disabled here in favour of GitHub actions? The project should ported from Travis to GH now.
> > 
> > 
> > Done.
> > > I'm not certain if it requires the Jazzband PyPI mirror key for correct release functionality on project level?
> > 
> > 
> > Yeah, lemme do this tomorrow when I'm in the office, don't merge this yet.
> > PS: I've added this PR to the tracking project: https://github.com/orgs/jazzband/projects/1
> 
> It looks like this isn't able to merge either since the Travis job won't trigger anymore and the status check is still required, hehe. If you can merge this later that would be nice.
I've updated the branch protection settings to require the new tests instead.

> The master branch is still pending a 1.4.0 release. The changelog and everything else is ready for running a release once the PyPI mirror keys are updated.
I've added the Jazzband release key as a secret to the repo.

**Review by jezdez — APPROVED** [review]

**Comment by jezdez** [comment]
Thank you all for working on this ❤️

**Pull request merged**
